// Auto-generated by scripts/src/transform-recipes.ts
// Full recipe-api.com data for future features (nutrition, equipment, dietary, etc.)
// Do NOT edit manually. Re-run the transform script to regenerate.

/* eslint-disable @typescript-eslint/no-explicit-any */

export const API_RECIPES: Map<string, any> = new Map([

]);
