// The Culinary Editorial — Color Palette
// Primary: Burnt Sienna (#9A4100) — all CTAs, active states, highlights
// Secondary: Soft Peach (#FDDCB5) — subtle backgrounds
// Background: Warm Cream (#FDF8F2) — main surface
// Card Surface: Pure White (#FFFFFF) — elevated cards
// Text Primary: Near-Black (#1A1A2E) — headlines and body
// Text Secondary: Mid-Gray (#666666) — metadata and captions
// Dark Mode: #0D0D0D background, burnt sienna accent preserved

const light = {
  primary: "#9A4100",
  primaryContainer: "#C05500",
  onPrimary: "#FFFFFF",
  onPrimaryContainer: "#FFFBFF",
  surface: "#FDF8F2",
  surfaceContainerLow: "#FFFFFF",
  surfaceContainerHigh: "#F5EFE8",
  surfaceContainerHighest: "#EDE7E0",
  surfaceContainer: "#FAF5EF",
  onSurface: "#1A1A2E",
  onSurfaceVariant: "#574238",
  secondary: "#666666",
  secondaryContainer: "#FDDCB5",
  onSecondaryContainer: "#775E3F",
  outlineVariant: "#DEC1B3",
  outline: "#8A7266",
  error: "#BA1A1A",
  success: "#2D7A4F",
  successContainer: "#E0F5E8",
  onSuccess: "#FFFFFF",
  warning: "#9A7B00",
  warningContainer: "#FEF3E0",
  surfaceWarm: "#FEF0E6",
  surfaceWarmAlt: "#F5EDDF",
  tertiary: "#005F9C",
  tertiaryContainer: "#0079C4",
  inverseSurface: "#1A1A2E",
  inverseOnSurface: "#F5F0EA",
  inversePrimary: "#FFB690",
  primaryFixedDim: "#FFB690",
  text: "#1A1A2E",
  background: "#FDF8F2",
  tint: "#9A4100",
  tabIconDefault: "#666666",
  tabIconSelected: "#9A4100",
};

const dark: typeof light = {
  primary: "#FFB690",
  primaryContainer: "#9A4100",
  onPrimary: "#552200",
  onPrimaryContainer: "#FFDCC8",
  surface: "#0D0D0D",
  surfaceContainerLow: "#1A1A1A",
  surfaceContainerHigh: "#2A2A2A",
  surfaceContainerHighest: "#353535",
  surfaceContainer: "#222222",
  onSurface: "#EDE0D4",
  onSurfaceVariant: "#D7C2B5",
  secondary: "#A0A0A0",
  secondaryContainer: "#594328",
  onSecondaryContainer: "#FBDAB3",
  outlineVariant: "#504336",
  outline: "#9E8C7E",
  error: "#FFB4AB",
  success: "#7BCC9B",
  successContainer: "#1A3D2A",
  onSuccess: "#003919",
  warning: "#E2C55E",
  warningContainer: "#3D3200",
  surfaceWarm: "#2E2118",
  surfaceWarmAlt: "#2A241E",
  tertiary: "#96CBFF",
  tertiaryContainer: "#004A7A",
  inverseSurface: "#EDE0D4",
  inverseOnSurface: "#1A1A2E",
  inversePrimary: "#9A4100",
  primaryFixedDim: "#FFB690",
  text: "#EDE0D4",
  background: "#0D0D0D",
  tint: "#FFB690",
  tabIconDefault: "#A0A0A0",
  tabIconSelected: "#FFB690",
};

export default { light, dark };
