// Auto-generated by scripts/src/transform-recipes.ts
// Do NOT edit manually. Re-run the transform script to regenerate.

export interface TransformedRecipe {
  id: string;
  countryId: string;
  title: string;
  description: string;
  image: string;
  category: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  difficulty: "Easy" | "Medium" | "Hard";
  ingredients: Array<{ id: string; name: string; amount: string }>;
  steps: Array<{ id: string; title: string; description: string }>;
  culturalNote: string;
  tips: string[];
}

export const TRANSFORMED_RECIPES: TransformedRecipe[] = [];
